import { assert, assertEquals } from './assert.ts';

/**
 * Tier B — the gateway integration tests. **All four §J authentication rows verified against a real
 * local gateway.**
 *
 * ════════════════════════════════════════════════════════════════════════════
 *  STATUS: §J.1, §J.2a, §J.2b and §J.2d — plus the separate CORS preflight, which
 *          is NOT one of the four authentication rows — have been executed against
 *          a real local Supabase Edge gateway (CLI 2.111.0, supabase-edge-runtime
 *          1.74.2) serving this repository's own `verify_jwt` declaration with no
 *          bypass flag. They pass, and every rejection was confirmed pre-handler.
 *  RUN AS: `tests/run-tier-b.ps1`, which brings up a disposable local stack, serves
 *          the function, and runs this suite with `NOOR_AI_GATEWAY_URL` and
 *          `NOOR_AI_LOCAL_GATEWAY_JWT_SECRET` set in the child process only.
 *          Without those variables the rows are reported ignored — never passed.
 * ════════════════════════════════════════════════════════════════════════════
 *
 * ── Why these cases cannot be moved into the pure tier ───────────────────────
 * `verify_jwt` is enforced by the **platform**, not by the handler. The documentation is explicit that
 * when the check fails "the platform returns a 401 error, and your code never executes". So the four rows below
 * are assertions about something that runs *before* any code in this repository — and a mock cannot stand in for
 * it, because mocking the gateway would mean writing the very component under test.
 *
 * §J is unusually clear about this, and it is why the rows are shaped the way they are:
 *
 *   • §J.1 — an unauthenticated request. "Deployed with `verify_jwt` enabled this is the **gateway's** platform
 *     401 and there is **no NoorLife `request_id`** — the test asserts that shape, not NoorLife's schema."
 *   • §J.2a — an invalid signature. "Asserted as 'a 401 with no provider call and no NoorLife body', **not** as
 *     NoorLife's error schema."
 *   • §J.2b — an expired token. "The producer is whichever runs first: the test accepts the gateway's platform
 *     shape **or** the handler's `unauthenticated`, because the documentation does not enumerate the gateway's
 *     per-claim checks." Observed: the **gateway** runs first, and the handler never starts.
 *   • §J.2d — this project's `sb_publishable_*` key sent as a bearer token. Per the documentation the platform
 *     "tries to parse it as a JWT and rejects the request with `Invalid JWT`", so it is "a
 *     **malformed-credential** rejection at the gateway and **does not** prove §D.4's check-6 role assertion".
 *
 * ── How §J.2b is signed without a key entering this repository ───────────────
 * This row was blocked for a long time, and the reason was real: an expired token only exercises §J.2b if it is
 * *correctly signed* — signed by the key the gateway actually trusts. A token signed by any other key is §J.2a,
 * which is a different row. The key that satisfies that condition lives in local CLI state, and §B.2's rule is
 * that no key material enters this repository.
 *
 * The rule is kept, in full. What changed is where the key is allowed to exist:
 *
 *   • the signing secret belongs to a **disposable local stack**, generated by `supabase start` and destroyed by
 *     `supabase stop --no-backup` in the same run. It is not the hosted project's key, and no hosted credential
 *     is read, needed or accepted here;
 *   • the harness captures it **without printing it** and hands it to this process through one environment
 *     variable, which it clears in a `finally`. It is never a command-line argument, never a file, never a
 *     fixture, never a log line and never committed;
 *   • the token is minted **inside this test process** from that value, used once against `127.0.0.1`, and
 *     discarded with the process.
 *
 * So the repository holds the *procedure*, and never the *material*. Reading this file tells you how the token
 * is produced; it does not tell you, and cannot be made to tell you, what it was signed with.
 *
 * ── Why the row needs a control request to mean anything ─────────────────────
 * A 401 on an expired token proves nothing on its own: a 401 is also what a wrong key, an unsupported algorithm
 * or a rejected issuer produces, and §J.2a already covers the wrong-key case. The assertion that the rejection
 * is *about `exp`* therefore rests on a paired control rather than on the response text:
 *
 *   • a **control** token — same key, same algorithm, same claims, `exp` in the future — is sent first. It gets
 *     through the gateway, and the reply is NoorLife's own envelope carrying a `request_id`, which only the
 *     handler can produce. That is what establishes the key is genuinely the one the gateway trusts;
 *   • the **expired** token — identical in every respect except `exp` — is refused with the platform's shape and
 *     no `request_id`, so the handler never ran.
 *
 * "Identical in every respect except `exp`" is a claim about the bytes, so the test proves it rather than
 * asserting it in prose. The shared claims are built **once** and both tokens are spread from that one object;
 * the signing helper generates nothing of its own — no uuid, no timestamp, no default — so it cannot introduce a
 * second variable; one frozen JOSE header object is passed to both; and before either token is signed the test
 * checks mechanically that the two claim sets carry the same keys in the same order, that exactly one key's
 * serialised value differs, and that the differing key is `exp`. An earlier revision minted a fresh `sub`,
 * `session_id` and `iat` per call, so the one-variable experiment it described was not the one it ran.
 *
 * Two requests differing in exactly one claim, with opposite outcomes. That is the evidence, and it does not
 * depend on reading a `code` string whose spelling is a runtime detail (§I.7).
 *
 * ── What the real gateway actually answered ──────────────────────────────────
 * Recorded because it differs from the documented shape, and §I.7 makes that AI-4's problem to absorb.
 * The hosted troubleshooting page documents a numeric `{ "code": 401, "message": … }`. Served locally,
 * supabase-edge-runtime 1.74.2 answers a **string** code and a duplicated message key:
 *
 *   §J.1   no Authorization       → 401 `{ "code": "UNAUTHORIZED_NO_AUTH_HEADER",     "message": …, "msg": … }`
 *   §J.2a  forged signature       → 401 `{ "code": "UNAUTHORIZED_ASYMMETRIC_JWT",     "message": …, "msg": … }`
 *   §J.2b  correctly signed, past → 401 `{ "code": "UNAUTHORIZED_LEGACY_JWT",         "message": …, "msg": … }`
 *   §J.2d  `sb_publishable_*`     → 401 `{ "code": "UNAUTHORIZED_INVALID_JWT_FORMAT", "message": …, "msg": … }`
 *   preflight `OPTIONS`           → 200, no credential required
 *
 * None of those is NoorLife's envelope and none carries a `request_id`, which is the property §C.9 relies on.
 * §J.2b's `code` is worth a second look: it names the *token family*, not the expiry, and it is the same family
 * the control token belongs to — so the code alone would not have distinguished the two. The control did. No
 * assertion below pins any of these spellings.
 *
 * That the rejections are genuinely pre-handler was confirmed independently of the body: the runtime logged each
 * failure from its own main worker, no `noor-ai` function worker booted for them, and the handler's single
 * structured log line never appeared. For §J.2b the runtime named the cause outright —
 * `code: "ERR_JWT_EXPIRED", claim: "exp", reason: "check_failed"` — while the control request in the same run
 * produced exactly one handler log line and a NoorLife body.
 *
 * ── The limit of what this tier shows ────────────────────────────────────────
 * This is evidence about a **local** gateway at the CLI and runtime versions named above. It is not proof of the
 * hosted project's behaviour, and the observed-shape divergence from the documented one is itself the reason to
 * keep that distinction: runtime version visibly matters. Deployment remains prohibited at this phase.
 *
 * ── How to run this tier ─────────────────────────────────────────────────────
 * `tests/run-tier-b.ps1` does all of it: Docker, the CLI, `supabase start`, `supabase functions serve`, this
 * suite with `--allow-net` scoped to the local gateway, then `supabase stop --no-backup`. Never
 * `--no-verify-jwt`: that flag would disable the single control this tier exists to test.
 *
 * They deliberately do **not** skip silently. A skipped test is invisible in a green run; a test that announces
 * "UNRUN — no local Supabase stack" is a line in the output that has to be read and answered for.
 */

/** Set to the served function's URL to run this tier. Absent on a machine with no local stack. */
const GATEWAY_URL = Deno.env.get('NOOR_AI_GATEWAY_URL') ?? null;

/**
 * The disposable local stack's own JWT signing secret, supplied by the harness for §J.2b only.
 *
 * Absent on any machine that is not running the harness, which is why §J.2b carries a second ignore condition
 * that the other rows do not. Nothing reads this except the minting helper below, and nothing prints it.
 */
const LOCAL_SIGNING_SECRET = Deno.env.get('NOOR_AI_LOCAL_GATEWAY_JWT_SECRET') ?? null;

type GatewayCase = {
  readonly row: string;
  readonly what: string;
  readonly expected: string;
  /**
   * Whether this row has a real executable case in this file, machine-checked below.
   *
   * This field exists because of a specific near-miss. An earlier version of this file recorded all four rows
   * as data while only three had a `Deno.test`, and the runner reported "4 ignored" — the fourth being the CORS
   * *preflight*, which is not an authentication row at all. Anyone counting the output would have concluded
   * §J.2b was covered. Prose could not stop that; an assertion can.
   */
  readonly executableCase: boolean;
};

/**
 * The four §J rows that belong to the gateway, with the assertion each makes.
 *
 * Recorded as data rather than as prose so the set is enumerable: a reader can see exactly what running the tier
 * covers, and that nothing was quietly dropped.
 */
const GATEWAY_CASES: readonly GatewayCase[] = [
  {
    row: '§J.1',
    what: 'no Authorization header at all',
    expected:
      '401 in Supabase’s platform shape — documented as { "code": 401, … }, observed locally as a string ' +
      'code — with NO NoorLife request_id, because the handler never ran',
    executableCase: true,
  },
  {
    row: '§J.2a',
    what: 'a well-formed JWT with a wrong or absent signature',
    expected: '401 with no provider call and no NoorLife body',
    executableCase: true,
  },
  {
    row: '§J.2b',
    what: 'a correctly signed token whose exp is in the past',
    expected:
      '401 from whichever producer runs first — the platform shape or the handler’s `unauthenticated` — ' +
      'asserting no NoorLife request_id is required; observed as the platform, pre-handler',
    executableCase: true,
  },
  {
    row: '§J.2d',
    what: 'this project’s sb_publishable_* key sent as Authorization: Bearer',
    expected:
      '401 as a malformed credential ("Invalid JWT"), proving a bundle-embedded key cannot reach the model; ' +
      'this does NOT prove §D.4’s check-6 role assertion',
    executableCase: true,
  },
];

Deno.test('TIER B — the gateway case set is complete, honestly labelled, and not substituted for', () => {
  /**
   * The one thing this file asserts unconditionally: that the row set is written down, and that nothing here
   * has quietly become a mock of the platform.
   *
   * The second assertion is the important one. §J.2d2 exists because a legacy `anon` key "would pass a signature
   * check and could satisfy the gate" — the gate is a real security control, and a fake one in this repository
   * would be a green test standing in for a control nobody verified.
   */
  assertEquals(GATEWAY_CASES.length, 4, 'four §J rows belong to the gateway');
  for (const gatewayCase of GATEWAY_CASES) {
    assert(gatewayCase.expected.includes('401'), `${gatewayCase.row} expects a 401`);
  }

  const source = Deno.readTextFileSync(
    new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'),
  );
  const executable = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

  /**
   * Every row claiming an executable case must actually have one.
   *
   * The prefix is matched rather than the bare row marker, because each row's own data entry already contains
   * its marker — a bare `includes('§J.2b')` would find the record of the row and call it a test. Only
   * a `Deno.test` name carries `TIER B — §J.2b`.
   */
  for (const gatewayCase of GATEWAY_CASES) {
    assertEquals(
      executable.includes(`TIER B — ${gatewayCase.row} `),
      gatewayCase.executableCase,
      `${gatewayCase.row}: executableCase=${gatewayCase.executableCase} must match whether a test exists`,
    );
  }
  assertEquals(
    GATEWAY_CASES.filter((c) => !c.executableCase).map((c) => c.row),
    [],
    'no gateway row is blocked — all four are executable against a real local gateway',
  );
  /**
   * The preflight is a §C.1 CORS case, not one of §J's authentication rows, and it is asserted separately so a
   * reader counting tests cannot mistake it for a fifth.
   */
  assert(
    executable.includes('the preflight is answered without a credential'),
    'the CORS preflight is checked separately from the authentication rows',
  );

  /**
   * §J.2b's key must never become a literal. The row is only meaningful while the secret arrives at runtime from
   * a disposable stack — a committed value would make this a test of a string in the repository, which is the
   * precise outcome §B.2 forbids and the reason the row stayed blocked for so long.
   */
  assertEquals(
    /LOCAL_SIGNING_SECRET\s*(=|\?\?)\s*['"`]/.test(executable),
    false,
    '§J.2b’s signing secret must come from the environment, never from a literal',
  );

  /**
   * The markers are assembled from fragments rather than written as literals, so this check cannot match its own
   * source. A scan whose pattern is its own first offender has to be either weakened or exempted, and both outcomes
   * end with the guard gone — which is how a real tier quietly becomes a mocked one.
   */
  const simulationMarkers = [
    ...['mock', 'fake', 'stub', 'simulate'].map((verb) => `${verb}Gateway`),
    ['verify', '_jwt', ' = true'].join(''),
    ['verify', '_jwt', ' = false'].join(''),
    ['--no', '-verify', '-jwt'].join(''),
  ];
  for (const marker of simulationMarkers) {
    assertEquals(
      executable.includes(marker),
      false,
      `this file must not simulate or bypass the gateway it tests (${marker})`,
    );
  }

  console.log(
    [
      '',
      '  ┌─ TIER B: GATEWAY INTEGRATION ───────────────────────────────────────',
      GATEWAY_URL === null
        ? '  │ NOOR_AI_GATEWAY_URL is unset, so no gateway is being reached and\n' +
          '  │ every row below is UNRUN here — ignored, never counted as passing.'
        : '  │ Reaching a real local Edge gateway. Rows marked RUN execute below.',
      '  │',
      ...GATEWAY_CASES.map((c) => {
        const needsSecret = c.row === '§J.2b';
        const state = GATEWAY_URL === null || (needsSecret && LOCAL_SIGNING_SECRET === null)
          ? 'UNRUN  '
          : 'RUN    ';
        return `  │ ${state} ${c.row.padEnd(7)} ${c.what}`;
      }),
      '  │',
      '  │ §J.2b additionally needs the disposable local stack’s own signing',
      '  │ secret, handed to this process by the harness and never committed.',
      '  │ Without it the row is UNRUN — it is never faked and never assumed.',
      '  │ The CORS preflight is a separate §C.1 case, not a fifth auth row.',
      '  └─────────────────────────────────────────────────────────────────────',
      '',
    ].join('\n'),
  );
});

/**
 * The runnable tier, which executes only when a gateway is actually there.
 *
 * `ignore` rather than an early `return`, so the runner reports these as ignored — visibly absent — rather than
 * as passing. A test that returns early on a missing precondition is a test that reads green while asserting
 * nothing, which is the specific outcome the phase brief forbids.
 */
Deno.test({
  name:
    'TIER B — §J.1 an unauthenticated request is refused by the gateway, in the platform’s shape',
  ignore: GATEWAY_URL === null,
  fn: async () => {
    const response = await fetch(`${GATEWAY_URL}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ contract_version: 1, message: 'Where is Qibla?' }),
    });

    assertEquals(response.status, 401, '§J.1 — the gateway refuses it');
    const body = await response.json();
    // §C.9 — the platform shape, and NO NoorLife request_id, because the handler never ran.
    assertEquals('request_id' in body, false, 'no NoorLife request_id for a pre-handler rejection');
    assertEquals('contract_version' in body, false, 'and not NoorLife’s envelope either');
    assertEquals('error' in body, false, 'nor NoorLife’s nested error object');

    /**
     * `code` is asserted as present, not as the number 401 — and this is a correction, not a relaxation.
     *
     * The hosted troubleshooting page documents `{ "code": 401, … }`. A real local gateway
     * (supabase-edge-runtime 1.74.2) instead answers `{ "code": "UNAUTHORIZED_NO_AUTH_HEADER", … }`: a string.
     * The earlier `code === 401` assertion was an assumption about the platform, and it was wrong; pinning
     * either spelling now would assert a runtime version rather than the contract. What §C.9 and §I.7 actually
     * rely on is that the body is *not NoorLife's* and carries no `request_id`, which the three assertions
     * above check — and the discriminating ones were strengthened, not loosened, when this was fixed.
     */
    assert(
      typeof body.code === 'number' || (typeof body.code === 'string' && body.code.length > 0),
      'the platform shape carries a code, numeric or string',
    );
    assert(
      typeof body.message === 'string' && body.message.length > 0,
      'and a human-readable message',
    );
  },
});

Deno.test({
  name: 'TIER B — §J.2a an invalidly signed token is refused with no NoorLife body',
  ignore: GATEWAY_URL === null,
  fn: async () => {
    const forged = `${btoa('{"alg":"ES256","typ":"JWT"}')}.${
      btoa('{"role":"authenticated"}')
    }.forged`;
    const response = await fetch(`${GATEWAY_URL}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${forged}` },
      body: JSON.stringify({ contract_version: 1, message: 'Where is Qibla?' }),
    });

    assertEquals(response.status, 401, '§J.2a — refused');
    const body = await response.json();
    assertEquals('contract_version' in body, false, 'not NoorLife’s schema');
    // The absence of a request_id is the evidence that this was refused before the handler, so a pre-handler
    // rejection can never be read back as a NoorLife handler response.
    assertEquals('request_id' in body, false, 'and no NoorLife request_id — the handler never ran');
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// §J.2b — the one row that needs a correctly signed token
// ─────────────────────────────────────────────────────────────────────────────

/** RFC 7515 §2 base64url: unpadded, URL-safe. Written out because the JOSE segments must be exact. */
function base64Url(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/**
 * The complete claim set of a local gateway token, written in the order the claims are serialised.
 *
 * Declared as a type rather than assembled ad hoc so that both §J.2b tokens are demonstrably the same shape:
 * a missing or extra claim would be a second variable, and a second variable is what makes the row
 * inconclusive.
 */
type LocalTokenClaims = {
  readonly iss: string;
  readonly sub: string;
  readonly aud: string;
  readonly role: string;
  readonly session_id: string;
  readonly iat: number;
  readonly exp: number;
};

/**
 * The one JOSE header both §J.2b tokens are signed under.
 *
 * A single frozen object passed to both signings, so the header segment is identical by construction rather
 * than by two literals happening to agree.
 */
const LOCAL_TOKEN_HEADER: Readonly<Record<string, string>> = Object.freeze({
  alg: 'HS256',
  typ: 'JWT',
});

/**
 * Sign a caller-supplied header and claim set as an HS256 JWT for the disposable local gateway.
 *
 * This helper **generates nothing**: no uuid, no timestamp, no default, no `Date.now()`. Every byte of both
 * JOSE segments comes from its arguments, which is what allows the caller to state — and to check — that two
 * tokens differ in exactly one claim. An earlier version generated `sub`, `session_id` and `iat` internally,
 * so every call produced a token that differed from the last in four places while the comment claimed one.
 *
 * `secret` is the local stack's own signing secret, read from the environment by the caller and held only in
 * this process. Nothing here writes, logs or returns it, and the token it produces is used once.
 */
async function signLocalToken(
  secret: string,
  header: Readonly<Record<string, string>>,
  claims: LocalTokenClaims,
): Promise<string> {
  const encoder = new TextEncoder();
  const signingInput = `${base64Url(encoder.encode(JSON.stringify(header)))}.${
    base64Url(encoder.encode(JSON.stringify(claims)))
  }`;
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const signature = new Uint8Array(
    await crypto.subtle.sign('HMAC', key, encoder.encode(signingInput)),
  );
  return `${signingInput}.${base64Url(signature)}`;
}

/**
 * The names of the claims whose serialised values differ between two claim sets.
 *
 * Returns key **names** only. No claim value, no serialised segment and no token leaves this function, so the
 * assertion built on it can report *which* claim varied without ever printing what it held.
 */
function differingClaimKeys(a: LocalTokenClaims, b: LocalTokenClaims): string[] {
  const left = a as unknown as Record<string, unknown>;
  const right = b as unknown as Record<string, unknown>;
  const keys = [...new Set([...Object.keys(left), ...Object.keys(right)])];
  return keys.filter((key) => JSON.stringify(left[key]) !== JSON.stringify(right[key]));
}

Deno.test({
  name:
    'TIER B — §J.2b a correctly signed token whose exp has passed is refused before the handler runs',
  /**
   * Two conditions, not one. The gateway alone is not enough for this row: without the disposable stack's
   * signing secret the best this could produce is a differently signed token, which is §J.2a wearing §J.2b's
   * name — the substitution that kept this row honestly blocked rather than quietly green.
   */
  ignore: GATEWAY_URL === null || LOCAL_SIGNING_SECRET === null,
  fn: async () => {
    const secret = LOCAL_SIGNING_SECRET as string;
    const origin = new URL(GATEWAY_URL as string).origin;
    const nowSeconds = Math.floor(Date.now() / 1000);

    /**
     * Everything the two tokens share, built once and read twice.
     *
     * One object, one `Date.now()`, one `randomUUID()` per claim. Both tokens are spread from this, so no
     * claim below can drift between them: there is only one value in existence for each.
     *
     * `iat` is deliberately older than either `exp` — an hour and two minutes back — so that both tokens are
     * internally coherent (issued, then expiring) and neither can be refused for an `iat` in the future. It is
     * the *same* `iat` for both, which is the point: the expired token is not "an older token", it is this
     * token with one field changed.
     */
    const commonClaims = {
      iss: `${origin}/auth/v1`,
      sub: crypto.randomUUID(),
      aud: 'authenticated',
      role: 'authenticated',
      session_id: crypto.randomUUID(),
      iat: nowSeconds - 3720,
    };
    const controlClaims: LocalTokenClaims = { ...commonClaims, exp: nowSeconds + 300 };
    const expiredClaims: LocalTokenClaims = { ...commonClaims, exp: nowSeconds - 3600 };

    /**
     * The one-variable experiment, checked before anything is signed.
     *
     * The whole row rests on the two requests differing in `exp` and in nothing else, and that is a property of
     * the bytes rather than of this comment. Three checks, none of which prints a claim value:
     *
     *   1. the same claim names in the same order, so `JSON.stringify` emits the same serialised layout;
     *   2. exactly one claim's serialised value differs, and it is `exp`;
     *   3. the serialised claim sets are byte-identical once `exp`'s digits are masked out — which is the
     *      direct statement of "only exp differs", made about the string that actually gets signed.
     *
     * If any of these fails the row stops here rather than sending a request it could not interpret.
     */
    assertEquals(
      Object.keys(controlClaims),
      Object.keys(expiredClaims),
      '§J.2b — both tokens must carry the same claim names in the same serialised order',
    );
    assertEquals(
      differingClaimKeys(controlClaims, expiredClaims),
      ['exp'],
      '§J.2b — the control and the expired claim set must differ in exactly one claim, and it must be exp',
    );
    const maskExp = (claims: LocalTokenClaims) =>
      JSON.stringify(claims).replace(/"exp":-?\d+/, '"exp":<varied>');
    assertEquals(
      maskExp(controlClaims) === maskExp(expiredClaims),
      true,
      '§J.2b — with exp masked the two serialised claim sets must be byte-identical',
    );

    /**
     * One frozen header object for both, and a helper that adds nothing of its own, so the only difference
     * that can reach the wire is the one asserted above.
     */
    const controlToken = await signLocalToken(secret, LOCAL_TOKEN_HEADER, controlClaims);
    const expiredToken = await signLocalToken(secret, LOCAL_TOKEN_HEADER, expiredClaims);
    /**
     * The same checks restated about the tokens themselves — compared as booleans, never as values, so no
     * serialised token can reach an assertion message or a failure report.
     */
    assertEquals(
      controlToken.split('.')[0] === expiredToken.split('.')[0],
      true,
      '§J.2b — both tokens must carry an identical JOSE header segment',
    );
    assertEquals(
      controlToken === expiredToken,
      false,
      '§J.2b — the two tokens must not be the same token',
    );

    /**
     * The control, and the reason this row means anything.
     *
     * Same key, same algorithm, same claims — `exp` in the future. If the gateway trusts this key, the request
     * gets past it and the reply is NoorLife's own envelope with a `request_id`, which only the handler can
     * produce. (The handler then refuses it on §D.6's documented grounds: it verifies against the platform's
     * asymmetric key set and cannot check an HS256 signature. A 401 either way — but a *NoorLife* 401.)
     *
     * If this assertion ever fails, the expired result below is uninterpretable and the row must be reported
     * inconclusive rather than passing: a 401 on the expired token would then be evidence of a rejected key
     * rather than of a rejected `exp`.
     */
    const control = await fetch(`${GATEWAY_URL}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${controlToken}`,
      },
      body: JSON.stringify({ contract_version: 1, message: 'Where is Qibla?' }),
    });
    const controlBody = await control.json();
    assert(
      'request_id' in controlBody,
      'CONTROL: an unexpired token signed with the same key must reach the handler — without that, a 401 on ' +
        'the expired token proves nothing about exp, and this row is inconclusive rather than passing',
    );

    /**
     * The row itself: the same claim set with `exp` an hour in the past, and nothing else touched.
     */
    const response = await fetch(`${GATEWAY_URL}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${expiredToken}`,
      },
      body: JSON.stringify({ contract_version: 1, message: 'Where is Qibla?' }),
    });

    assertEquals(response.status, 401, '§J.2b — an expired token is refused');
    const body = await response.json();

    /**
     * §J.2b permits either producer, so the assertion §J actually requires is the narrow one: no NoorLife
     * `request_id` may be *required*. What this gateway does is stronger, and it is asserted as observed —
     * the rejection is pre-handler, proved by the same property that separates the control from this request.
     */
    assertEquals(
      'request_id' in body,
      false,
      '§J.2b — refused before the handler, so no NoorLife request_id',
    );
    assertEquals('contract_version' in body, false, 'and not NoorLife’s envelope');
    assertEquals('error' in body, false, 'nor NoorLife’s nested error object');
    assert(
      typeof body.code === 'number' || (typeof body.code === 'string' && body.code.length > 0),
      'the platform shape carries a code, numeric or string',
    );

    /**
     * The discriminating assertion, stated as the comparison it is: the one claim that differed — proved to be
     * the only one, above, before either token was signed — flipped the outcome from "the handler answered" to
     * "the handler never ran". The response `code` is deliberately not pinned: §I.7 treats it as opaque, and
     * here it names the token family rather than the expiry, so it is the *pair* of results that identifies
     * `exp` as the cause, not the string.
     */
    assert(
      'request_id' in controlBody && !('request_id' in body),
      '§J.2b — exp was the only claim that differed between the two requests, and only the expired one was ' +
        'refused before the handler',
    );
  },
});

Deno.test({
  name: 'TIER B — §J.2d a publishable key sent as a bearer token cannot reach the model',
  ignore: GATEWAY_URL === null,
  fn: async () => {
    /**
     * §J.2d proves "a bundle-embedded key cannot reach the model". The value below is an obvious placeholder,
     * not this project's key: §B.2 keeps real key material out of the repository, and the assertion is about the
     * *shape* being rejected rather than about any particular key.
     */
    const response = await fetch(`${GATEWAY_URL}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: 'Bearer sb_publishable_placeholder_not_a_real_key',
      },
      body: JSON.stringify({ contract_version: 1, message: 'Where is Qibla?' }),
    });

    assertEquals(response.status, 401, '§J.2d — a non-JWT credential is refused as malformed');
    const body = await response.json();
    assertEquals(
      'request_id' in body,
      false,
      'refused before the handler, so no NoorLife request_id',
    );
    /**
     * The rejection is a *format* rejection, which is exactly the limit §J.2d records. Observed locally as
     * `UNAUTHORIZED_INVALID_JWT_FORMAT`: the gateway never got far enough to look at a `role`, so this proves a
     * bundle-embedded key cannot reach the model and proves nothing about §D.4's check-6 role assertion. That
     * remains §J.2d2's job, on the handler side.
     */
    assertEquals('contract_version' in body, false, 'and not NoorLife’s envelope');
  },
});

Deno.test({
  name: 'TIER B — the preflight is answered without a credential',
  ignore: GATEWAY_URL === null,
  fn: async () => {
    // §C.1 — a preflight "requires no authentication (a preflight carries no `Authorization` header by
    // definition)". Worth checking against the real gateway, because whether the platform intercepts `OPTIONS`
    // before the JWT gate is behaviour this repository cannot determine by reading its own code.
    const response = await fetch(`${GATEWAY_URL}`, { method: 'OPTIONS' });
    assert(response.status < 400, `a preflight must not be refused (got ${response.status})`);
    await response.body?.cancel();
  },
});
