import { withAndroidManifest, type AndroidConfig, type ConfigPlugin } from '@expo/config-plugins';

/**
 * Android 11+ package visibility for `mailto:` — the "Open Email App" button on Reset Link Sent.
 *
 * ── The defect this exists to fix ────────────────────────────────────────────
 * `ResetLinkSentScreen` asks `Linking.canOpenURL('mailto:')` before opening a mail client. On
 * Android that call lands in React Native's `IntentModule.canOpenURL`, which builds
 * `Intent(ACTION_VIEW, "mailto:")` and returns `intent.resolveActivity(packageManager) != null`.
 *
 * Since API 30, `resolveActivity` only sees packages this app is *allowed* to see. An app that
 * targets 30 or higher — this one targets 36, via `expo-root-project` — gets an empty view of the
 * package list except for what its own `<queries>` block declares. The prebuild template declares
 * exactly one query, `VIEW` + `BROWSABLE` + `https`, which is why web links resolve and mail does
 * not. Gmail can be installed and working, `adb shell am start -a android.intent.action.MAIN -c
 * android.intent.category.APP_EMAIL` can launch it from outside, and the probe still returns false,
 * so the screen shows its honest "no email app" message for the wrong reason.
 *
 * Declaring `SENDTO` + `mailto` makes mail clients visible to this app. Visibility is granted per
 * *package*, not per query: once a package matches any declared `<intent>`, it becomes resolvable
 * for other intents too, so the `ACTION_VIEW` probe starts succeeding without needing its own entry.
 * That keeps the declaration at the single narrowest one Android documents for "apps that handle
 * email", rather than widening to `QUERY_ALL_PACKAGES` or an explicit package list.
 *
 * ── Why a config plugin rather than an edit to the manifest ──────────────────
 * `android/` is not in the repository — `.gitignore` ends with `/ios` and `/android`, and
 * `git ls-files android` returns nothing. The manifest is generated by `expo prebuild`, so a
 * hand-edit is undone by the next regeneration. There is no `android.queries` field in the Expo app
 * config either (SDK 57 exposes `intentFilters`, which writes *this* app's filters, not the queries
 * that let it see other apps). A local plugin registered in `app.json` is the durable place.
 *
 * The screen itself is deliberately untouched. Its `try`/`catch` and no-mail-app fallback are still
 * correct and still needed: a device with genuinely no mail client must keep saying so.
 */

type AndroidManifest = AndroidConfig.Manifest.AndroidManifest;
type ManifestQuery = AndroidConfig.Manifest.ManifestQuery;
type ManifestQueryIntent = NonNullable<ManifestQuery['intent']>[number];

export const MAILTO_QUERY_ACTION = 'android.intent.action.SENDTO';
export const MAILTO_QUERY_SCHEME = 'mailto';

function isMailtoQueryIntent(intent: ManifestQueryIntent): boolean {
  const sendsTo = (intent.action ?? []).some(
    (action) => action.$['android:name'] === MAILTO_QUERY_ACTION,
  );
  const mailto = (intent.data ?? []).some(
    (data) => data.$['android:scheme'] === MAILTO_QUERY_SCHEME,
  );
  return sendsTo && mailto;
}

/** Whether the manifest already declares the `SENDTO` + `mailto` query, in any `<queries>` block. */
export function hasMailtoQuery(androidManifest: AndroidManifest): boolean {
  return (androidManifest.manifest.queries ?? []).some((query) =>
    (query.intent ?? []).some(isMailtoQueryIntent),
  );
}

/**
 * Adds the `SENDTO` + `mailto` intent query, in place, and returns the same manifest.
 *
 * Appends to the existing `<queries>` element rather than adding a second one, so the template's
 * `https` query is preserved and the merged manifest keeps a single block.
 *
 * Re-running is a no-op. SDK 57's `expo prebuild` regenerates `android/` from the template on every
 * run — even without `--clean`, which was observed rather than assumed — so today's runs each start
 * from a manifest with only the `https` query. The guard is for the cases where that is not true: a
 * mod chain that applies this plugin more than once, and any future prebuild that patches an
 * existing manifest in place instead of recreating it. Neither should stack a duplicate intent.
 */
export function addMailtoQuery(androidManifest: AndroidManifest): AndroidManifest {
  const { manifest } = androidManifest;
  const queries: ManifestQuery[] = manifest.queries ?? [];
  manifest.queries = queries;

  if (hasMailtoQuery(androidManifest)) {
    return androidManifest;
  }

  const mailtoIntent: ManifestQueryIntent = {
    action: [{ $: { 'android:name': MAILTO_QUERY_ACTION } }],
    data: [{ $: { 'android:scheme': MAILTO_QUERY_SCHEME } }],
  };

  const existing = queries[0];
  if (existing) {
    existing.intent = [...(existing.intent ?? []), mailtoIntent];
  } else {
    queries.push({ intent: [mailtoIntent] });
  }

  return androidManifest;
}

const withMailtoPackageVisibility: ConfigPlugin = (config) =>
  withAndroidManifest(config, (androidConfig) => {
    androidConfig.modResults = addMailtoQuery(androidConfig.modResults);
    return androidConfig;
  });

export default withMailtoPackageVisibility;
