import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import withMailtoPackageVisibility, {
  MAILTO_QUERY_ACTION,
  MAILTO_QUERY_SCHEME,
  addMailtoQuery,
  hasMailtoQuery,
} from '../with-mailto-package-visibility';

import type { AndroidConfig } from '@expo/config-plugins';

/**
 * Package visibility for `mailto:`, asserted at the two places it can be lost.
 *
 * The transformation is unit-tested against a manifest shaped like the one `expo prebuild` writes,
 * because that is where the regressions live: replacing the `<queries>` block instead of appending
 * to it would silently drop the `https` query that Custom Tabs and the auth callback rely on, and a
 * non-idempotent append would stack duplicate intents anywhere the plugin runs twice over the same
 * manifest.
 *
 * The transformation running at all then depends on `app.json` registering the plugin, which is the
 * second place this can be lost and is checked separately below.
 *
 * ── Why nothing here reads the generated manifest ────────────────────────────
 * An earlier version of this file asserted against `android/app/src/main/AndroidManifest.xml`. That
 * was wrong for a test: `android/` is generated by `expo prebuild` and is gitignored, so a clean
 * checkout or a CI run has no such file and the suite would fail for a reason that has nothing to do
 * with this plugin. Both inputs asserted here — the plugin module and `app.json` — are
 * source-controlled, so this suite passes on a checkout that has never been prebuilt.
 *
 * The generated manifest is still worth inspecting; it is just a local validation step and a report
 * artifact, not a Jest prerequisite.
 */

type AndroidManifest = AndroidConfig.Manifest.AndroidManifest;

const ROOT = join(__dirname, '..', '..');
const APP_CONFIG = join(ROOT, 'app.json');

/** Exactly the string `app.json` has to carry for Expo to resolve this plugin. */
const PLUGIN_REFERENCE = './plugins/with-mailto-package-visibility';

type AppConfig = { expo?: { plugins?: (string | unknown[])[] } };

/** The plugin references `app.json` declares, with the `[name, options]` tuple form flattened. */
function registeredPlugins(): string[] {
  const config = JSON.parse(readFileSync(APP_CONFIG, 'utf8')) as AppConfig;
  return (config.expo?.plugins ?? []).map((entry) =>
    Array.isArray(entry) ? String(entry[0]) : String(entry),
  );
}

/** The `https` query the prebuild template ships, and the only one present before this fix. */
function templateManifest(): AndroidManifest {
  return {
    manifest: {
      $: { 'xmlns:android': 'http://schemas.android.com/apk/res/android' },
      queries: [
        {
          intent: [
            {
              action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
              category: [{ $: { 'android:name': 'android.intent.category.BROWSABLE' } }],
              data: [{ $: { 'android:scheme': 'https' } }],
            },
          ],
        },
      ],
    },
  };
}

function intentsOf(manifest: AndroidManifest) {
  return (manifest.manifest.queries ?? []).flatMap((query) => query.intent ?? []);
}

function mailtoIntents(manifest: AndroidManifest) {
  return intentsOf(manifest).filter(
    (intent) =>
      (intent.action ?? []).some((action) => action.$['android:name'] === MAILTO_QUERY_ACTION) &&
      (intent.data ?? []).some((data) => data.$['android:scheme'] === MAILTO_QUERY_SCHEME),
  );
}

function httpsIntents(manifest: AndroidManifest) {
  return intentsOf(manifest).filter((intent) =>
    (intent.data ?? []).some((data) => data.$['android:scheme'] === 'https'),
  );
}

describe('addMailtoQuery', () => {
  it('adds a SENDTO + mailto intent query, which is what makes mail apps visible', () => {
    const manifest = templateManifest();
    expect(hasMailtoQuery(manifest)).toBe(false);

    addMailtoQuery(manifest);

    expect(mailtoIntents(manifest)).toHaveLength(1);
    expect(hasMailtoQuery(manifest)).toBe(true);
  });

  it('keeps the existing https query rather than replacing the queries block', () => {
    // Dropping this would break Custom Tabs and the auth callback, and nothing in the mail flow
    // would look any different — so it is asserted rather than assumed.
    const manifest = templateManifest();

    addMailtoQuery(manifest);

    expect(httpsIntents(manifest)).toHaveLength(1);
    expect(manifest.manifest.queries).toHaveLength(1);
  });

  it('is idempotent, so applying it twice cannot stack a duplicate intent', () => {
    const manifest = templateManifest();

    addMailtoQuery(manifest);
    addMailtoQuery(manifest);
    addMailtoQuery(manifest);

    expect(mailtoIntents(manifest)).toHaveLength(1);
    expect(httpsIntents(manifest)).toHaveLength(1);
  });

  it('creates a queries block when the manifest has none', () => {
    const manifest: AndroidManifest = {
      manifest: { $: { 'xmlns:android': 'http://schemas.android.com/apk/res/android' } },
    } as AndroidManifest;

    addMailtoQuery(manifest);

    expect(mailtoIntents(manifest)).toHaveLength(1);
  });

  it('does not widen visibility beyond the one intent the defect needs', () => {
    // No `<package>` allow-list and no second intent: package visibility is granted per package, so
    // one matching query is enough to make a mail client resolvable for the ACTION_VIEW probe too.
    const manifest = templateManifest();

    addMailtoQuery(manifest);

    const queries = manifest.manifest.queries ?? [];
    expect(queries.flatMap((query) => query.package ?? [])).toHaveLength(0);
    expect(intentsOf(manifest)).toHaveLength(2);
  });
});

describe('app.json', () => {
  it('registers the plugin, without which the transformation never runs', () => {
    // The failure this catches is the quiet one: the plugin file can be perfect and every test
    // above can pass while the device still reports "no email app is available", because nothing
    // asked Expo to apply it.
    expect(registeredPlugins()).toContain(PLUGIN_REFERENCE);
  });

  it('registers it exactly once, so the mod does not run twice', () => {
    const matches = registeredPlugins().filter((reference) => reference === PLUGIN_REFERENCE);

    expect(matches).toHaveLength(1);
  });

  it('names a plugin file that is actually on disk', () => {
    // Guards the typo that `expo prebuild` would only report at build time, and pins the reference
    // to a source-controlled file rather than anything generated.
    expect(existsSync(join(ROOT, `${PLUGIN_REFERENCE}.ts`))).toBe(true);
  });

  it('keeps the other plugins it already declared', () => {
    // This entry was appended to an existing list; dropping a sibling would be a silent regression
    // in splash screen or secure store setup.
    expect(registeredPlugins()).toEqual(
      expect.arrayContaining(['expo-router', 'expo-splash-screen', 'expo-secure-store']),
    );
  });
});

describe('the plugin export', () => {
  it('is a function, which is what Expo requires of a config plugin', () => {
    // `resolveConfigPluginExport` throws INVALID_PLUGIN_TYPE on anything else, and that failure
    // would only surface during a prebuild.
    expect(typeof withMailtoPackageVisibility).toBe('function');
  });
});
